Repository UBC-MDS/DSCI-532_gr202_r_dashboard, pull requests merged in 2019-12, with the labels that each got.

#3 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#4 Add PROPOSAL.md
  PROPOSAL.md
Labels: documentation

#5 Update README from milestone 2
  README.md
Labels: documentation

#7 Upload sketch draft and trend plot screenshot
  img/sketch.jpg
  img/trendplot_screenshot.png
Labels: documentation

#8 update readme and add screenshots
  README.md
  img/heatmap_screenshot.png
  img/map_screenshot.png
  img/process_screenshot.jpg
Labels: documentation

#9 Update sketch and progress screenshot
  img/bar_screenshot.png
  img/process_screenshot.jpg
  img/sketch.jpg
Labels: documentation

#14 Updated dictionary comprehensions to sort alphabetically
  app.R
Labels: enhancement

#17 [ENH] add trend plot to app.R
  app.R
Labels: enhancement

#16 Added heatmap functions
  app.R
Labels: enhancement

#18 created function to make the dataframe for crime bar plot, created gg…
  app.R
Labels: enhancement

#25 Added theme_minimal() to all graphs
  app.R
Labels: enhancement

#29 fixed initial filter bug #28
  app.R
Labels: bug

#31 fixed bug #30 so initial load shows all years
  app.R
Labels: bug

#33 [ENH] list filter default values in alphabetical order
  app.R
Labels: enhancement

#32 Add footer
  app.R
Labels: enhancement

#38 Add deployment files
  Aptfile
  Procfile
  app.json
  init.R
Labels: documentation

#39 [ENH] sorted days in heatmap
  app.R
Labels: enhancement

#40 Updated Tooltips for more descriptive text
  app.R
Labels: enhancement

#44 [DOC] Update app.json with lubridate
  app.R
  init.R
Labels: documentation

#45 removed unnecessary function (toTitleCase)
  app.R
Labels: enhancement

#47 changed trend graph to multiline graph
  app.R
Labels: enhancement

#48 Updated Bargraph, so now it's ordered in a descending fashion from th…
  app.R
Labels: enhancement

#50 update preview screenshot
  README.md
  img/preview.png
Labels: documentation

#52 updated tooltip for heatmap and choropleth map and added roxygen
  app.R
Labels: documentation, enhancement

#55 Fixed tooltip for heatmap and bar chart
  app.R
Labels: enhancement
